#--This is configuration file for Teradata to Bigquery conversion
DIRECT_MAP:
  CREATE SET TABLE: CREATE OR REPLACE TABLE
  CREATE MULTISET TABLE: CREATE OR REPLACE TABLE
  NO BEFORE JOURNAL,: ""
  NO AFTER JOURNAL,: ""
  CHECKSUM = DEFAULT,: ""
  DEFAULT MERGEBLOCKRATIO,: ""
  DEFAULT MERGEBLOCKRATIO: ""
  CHARACTER SET LATIN NOT CASESPECIFIC: ""
  CHARACTER SET UNICODE NOT CASESPECIFIC: ""
  DATE FORMAT 'YYYY-MM-DD': DATE
  ',FALLBACK ,': ""
  ',NO FALLBACK ,': ""
  MAP = TD_MAP1: ""
  CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL: ""
  CHAR\([0-9]*\) : STRING     #Pattern CHAR(#), exmaple CHAR(5) or CHAR(4000)
  VARBYTE: BYTES
  NUMBER : NUMERIC
  DECIMAL\([0-9]*,[0-9]*\) : NUMERIC
  DECIMAL : NUMERIC
  FLOAT\([0-9]*,[0-9]*\) : NUMERIC  #Pattern FLOAT(#,#), exmaple FLOAT(5,5) or FLOAT(23,5)
  FLOAT : NUMERIC
  BIGINT : INT64
  INTEGER : INT64
  SMALLINT : INT64
  BYTEINT : BOOL
  BLOB : STRING
  BYTE : BYTES
  'SEL ' : SELECT
  LOCKING ROW FOR ACCESS : ''
  LOCKING  ROW FOR ACCESS : ''
  GENERATED BY DEFAULT AS IDENTITY : ''
  REPLACE VIEW : CREATE OR REPLACE VIEW
  LOCKING    ROW FOR ACCESS: ''